remote_theme: daviddarnes/alembic@main
# remote_theme: mistakes/minimal-mistakes@master
plugnis:
  - jeykill-remote-pull

title: Art Categorizer
description: An art classification model classifies 15 different art styles.

author:
  name: Syed Mohammed Mostaque Billah
